language: node_js
node_js:
  - "8"
dist: trusty
sudo: required
addons:
  chrome: stable
  hostname: localhost
services:
  - mongodb
  - redis-server
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
env:
  - NODE_ENV=ci
  - PORT=3000
before_script:
  - npm run start &
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
notifications:
  email: false
script:
  - npm run test
