language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci
  - PORT=3000
before_script:
  - npm run start &
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - sleep 15
  - npm run test
