language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
addons:
  chrome: stable
  hosts:
    - localhost
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci
  - PORT=3000
before_script:
  - nohup npm run start &
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - sleep 15
  - npm run test
