language: node_js
node_js:
  - "8"
sudo: required
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
  chrome: stable
notifications:
  email: false
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci
  - PORT=5000
cache:
  directories:
    - node_modules
    - client/node_modules
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - npm install
  - npm run build
before_script:
  - npm run start &
script:
  - npm run test
